name: Build DEB Packages 
on: 
  push: 
    branches: 
      - main 
jobs: 
  build: 
    runs - on: ubuntu - latest 
    steps: 
      - name: Set up job 
        run: echo "Job setup" 
      - name: Checkout code 
        uses: actions/checkout@v4.2.2 
      - name: Check cache 
        uses: actions/cache@v4.2.1 
      - name: Prepare Theos 
        run: echo "Preparing Theos" 
      - name: Setup GNU Make 
        run: echo "Setting up GNU Make" 
      - name: Build package 
        run: echo "Building package" 
      - name: Upload artifact 
        uses: actions/upload - artifact@v4.6.0 
        with: 
          name: my - artifact 
          path: output/ 
      - name: Post - Run cache 
        uses: actions/cache@v4.2.1 
      - name: Post - Run checkout 
        uses: actions/checkout@v4.2.2