name: Build & Sync

on: 
  push:
    branches: [ main ]
  pull_request:
  schedule: 
    - cron: '0 2 * * *'  # 每天UTC时间2点自动同步[3,5](@ref)

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 原有构建步骤保持不变
      - uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Check cache
        run: |
          echo "upstream_heads=$(git ls-remote https://github.com/roothide/theos | head -n1 | cut -f1)-$(git ls-remote https://github.com/theos/sdks | head -n1 | cut -f1)" >> $GITHUB_ENV

      - name: Use cache
        id: cache
        uses: actions/cache@v4.2.1
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ runner.os }}-${{ env.upstream_heads }}

      - name: Prepare Theos
        uses: huami1314/theos-action@main

      - name: Setup GNU Make
        run: |
          echo "$(brew --prefix)/opt/make/libexec/gnubin" >> $GITHUB_PATH

      - name: Build package
        run: |
          rm -f packages/*
          make package FINALPACKAGE=1 -j$(sysctl -n hw.ncpu)
          make package THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1 -j$(sysctl -n hw.ncpu)
          make package THEOS_PACKAGE_SCHEME=roothide FINALPACKAGE=1 -j$(sysctl -n hw.ncpu)

      - name: Upload specific Deb packages
        uses: actions/upload-artifact@v4.6.0
        with:
          name: DYYY
          path: ${{ github.workspace }}/packages/*.deb

  sync-fork:  # 新增同步任务[3,5](@ref)
    needs: build  # 确保在构建完成后执行
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 同步上游仓库
        uses: TG908/fork-sync@v1.6.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: roothide  # 上游仓库的拥有者
          head: main       # 上游仓库的分支
          base: main       # 本地仓库的分支
