# File: .github/workflows/build.yml
name: Ultimate Build Flow

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Force Sync Fork
        env:
          UPSTREAM_REPO: 873116202/DYYY
          TARGET_BRANCH: main
        run: |
          git remote add upstream "https://github.com/${UPSTREAM_REPO}.git"
          git fetch upstream --force
          git reset --hard upstream/$TARGET_BRANCH
          git push origin "$TARGET_BRANCH" --force

  build:
    needs: sync
    runs-on: macos-13
    timeout-minutes: 10
    env:
      THEOS_ROOT: ${{ github.workspace }}/theos
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Core Dependencies
        run: |
          # 修复brew更新问题
          export HOMEBREW_NO_INSTALL_CLEANUP=1
          brew update-reset
          brew install --force-bottle make ldid

          # 修复Perl模块安装
          echo "install --force" | sudo tee -a ~/.cpan/CPAN/MyConfig.pm
          yes | sudo cpan -T File::Which XML::Parser

      - name: Setup Theos SDK
        run: |
          mkdir -p $THEOS_ROOT/sdks
          git clone --filter=blob:none --depth=1 \
            https://github.com/theos/sdks.git $THEOS_ROOT/sdks

          # 验证SDK存在性
          if [ ! -d "$THEOS_ROOT/sdks/iPhoneOS14.5.sdk" ]; then
            echo "::error::Missing critical SDK files"
            exit 1
          fi

      - name: Build Process
        run: |
          export PATH="$THEOS_ROOT/bin:$PATH"
          make clean
          
          # 安全构建参数
          export THEOS_PACKAGE_SCHEME=roothide
          export FINALPACKAGE=1
          export THEOS_MAKE_PARALLEL=no

          # 分步构建
          make stage && \
          make package || exit 1

      - name: Artifact Control
        uses: actions/upload-artifact@v4
        with:
          name: Production-Binaries
          path: packages/*.deb
          if-no-files-found: error
