name: Build & Auto Sync 
 
on:
  schedule:
    - cron: "0 16 * * *"  # UTC+8 时间每天8点执行 
  push:
    branches: [ main ]
  pull_request:
 
jobs:
  build:
    runs-on: macos-latest 
    permissions:
      contents: write  # 需要仓库写权限 
 
    steps:
      # 同步上游仓库（仅定时任务触发）
      - name: Sync Fork Repository 
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add upstream https://github.com/roothide/theos.git 
          git fetch upstream 
          git checkout main 
          git merge upstream/main -X theirs 
          git push "https://x-access-token:${FORK_PAT}@github.com/873116202/DYYY.git" main 
        env:
          FORK_PAT: ${{ secrets.FORK_PAT }}
        if: github.event_name == 'schedule'
 
      # 初始化仓库（所有触发条件）
      - name: Checkout code 
        uses: actions/checkout@v4
        with:
          submodules: true 
          fetch-depth: 0  # 保留完整提交历史 
 
      # 缓存策略优化 
      - name: Calculate cache key 
        run: |
          UPSTREAM_HEADS=$(git ls-remote https://github.com/roothide/theos | head -n1 | cut -f1)
          SDK_HEADS=$(git ls-remote https://github.com/theos/sdks | head -n1 | cut -f1)
          echo "CACHE_KEY=macos-$UPSTREAM_HEADS-$SDK_HEADS" >> $GITHUB_ENV 
 
      - name: Restore cache 
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/theos 
            ${{ github.workspace }}/.theos 
          key: ${{ env.CACHE_KEY }}
          restore-keys: |
            macos-
            ${{ runner.os }}-
 
      # 构建流程（根据实际需求补充）
      - name: Build Project 
        run: |
          # 示例构建命令（根据实际项目修改）
          ./bootstrap.sh 
          make package 
 
      # 构建后验证（可选）
      - name: Validate Build 
        run: |
          ls -l *.deb  # 检查构建产物存在性
          file *.deb   # 验证文件类型 
 
      # 错误处理 
      - name: Handle Errors 
        if: failure()
        run: |
          echo "Build Failed: $(date)"
          git log -1  # 记录失败时的提交信息 
 
      # 通知（可选）
      - name: Notify on Failure 
        if: failure()
        uses: appleboy/scrapbox-action@v1
        with:
          token: ${{ secrets.SCRAPBOX_TOKEN }}
          message: "Build Failed: ${GITHUB_SHA}"