# File: .github/workflows/build.yml
name: Robust Build System

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'

jobs:
  precheck:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Validate Workflow
        uses: actions/checkout@v4
      - name: Syntax Check
        run: |
          ruby -e "require 'yaml'; YAML.load_file('.github/workflows/build.yml')"
        shell: bash

  sync:
    needs: precheck
    runs-on: ubuntu-latest
    steps:
      - name: Secure Sync
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Merge Upstream
        env:
          UPSTREAM: 873116202/DYYY
        run: |
          git config --global pull.rebase false
          git remote add upstream "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${UPSTREAM}.git"
          git pull --commit --no-edit upstream main
          git push origin main

  build:
    needs: [precheck, sync]
    runs-on: macos-13
    env:
      THEOS: ${{ github.workspace }}/theos
    steps:
      - name: Safe Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Core Setup
        run: |
          # 强制清理缓存
          brew cleanup -s
          # 原子化依赖安装
          {
            brew install make ldid &&
            sudo cpan -T File::Which
          } || exit 1

      - name: Theos Bootstrap
        run: |
          mkdir -p $THEOS
          git clone --depth 1 https://github.com/roothide/theos.git $THEOS
          ln -sf $THEOS/sdks $THEOS/vendor/sdks || true

      - name: Guaranteed Build
        timeout-minutes: 8
        run: |
          export PATH="$THEOS/bin:$PATH"
          make clean
          make package \
            THEOS_PACKAGE_SCHEME=roothide \
            FINALPACKAGE=1 \
            DEBUG=0 \
            -j$(($(sysctl -n hw.ncpu)/2))
