name: Build & Auto Sync 

on:
  schedule:
    - cron: "0 16 * * *"  # UTC时间0点（北京时间8点）执行 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest 
    permissions:
      contents: write

    steps:
      # 同步上游仓库（仅定时任务触发）
      - name: Sync Fork Repository 
        if: github.event_name == 'schedule'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add upstream https://github.com/roothide/theos.git
          git fetch upstream
          git checkout -B main upstream/main
          git push --force "https://x-access-token:${{ secrets.FORK_PAT }}@github.com/873116202/DYYY.git" main 
        env:
          GITHUB_PAT: ${{ secrets.FORK_PAT }}

      # 代码检出
      - name: Checkout code 
        uses: actions/checkout@v4
        with:
          submodules: true 

      # 构建流程精简版
      - name: Build Project 
        run: |
          ./bootstrap.sh
          make package

      # 基础验证
      - name: Validate Build 
        run: |
          ls -l *.deb
          file *.deb

      # 错误处理（保留日志功能）
      - name: Upload Build Log
        if: failure()
        uses: actions/upload-artifact@v3
        with: 
          name: build-error-log
          path: |
            build.log
