# File: .github/workflows/main.yml
name: Sync & Build

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # 每天UTC时间2点自动运行

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Sync from Upstream
        env:
          UPSTREAM_REPO: 873116202/DYYY
          UPSTREAM_BRANCH: main
        run: |
          git remote add upstream https://github.com/$UPSTREAM_REPO
          git fetch upstream
          git merge --no-edit upstream/$UPSTREAM_BRANCH
          git push origin $UPSTREAM_BRANCH

  build:
    needs: sync-fork
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Build Environment
        run: |
          # 安装必要依赖
          brew install -q make perl ldid
          sudo cpan -i -q File::Which
          
          # 配置Theos
          git clone https://github.com/roothide/theos.git
          export THEOS=$PWD/theos
          echo "THEOS=$THEOS" >> $GITHUB_ENV
          
          # 安装SDK
          mkdir -p $THEOS/sdks
          git clone https://github.com/theos/sdks.git $THEOS/sdks

      - name: Build Packages
        run: |
          export PATH="$THEOS/bin:$PATH"
          rm -rf packages/*.deb
          
          # 并行构建
          schemes=(rootless roothide)
          for scheme in "${schemes[@]}"; do
            make clean
            make package \
              THEOS_PACKAGE_SCHEME=$scheme \
              FINALPACKAGE=1 \
              -j$(sysctl -n hw.ncpu)
          done

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DYYY-Packages
          path: packages/*.deb
          retention-days: 3
