name: Build & Auto Sync 
 
on:
  schedule:
    - cron: "0 16 * * *"  # 每天UTC时间0点执行（北京时间8点）
  push:
    branches: [ main ]
  pull_request:
 
jobs:
  build:
    runs-on: macos-latest 
    permissions:
      contents: write  # 允许推送代码到仓库 
 
    steps:
      # 同步上游仓库（仅定时任务触发）
      - name: Sync Fork Repository 
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add upstream https://github.com/roothide/theos.git 
          git fetch upstream 
          git checkout main 
          git merge upstream/main -X theirs 
          git push "https://x-access-token:${{ secrets.FORK_PAT }}@github.com/873116202/DYYY.git" main 
        env:
          GITHUB_PAT: ${{ secrets.FORK_PAT }}
        if: github.event_name == 'schedule'  # 仅定时任务触发同步 
 
      # 构建流程（与历史配置保持一致）
      - uses: actions/checkout@v4
        with:
          submodules: true 
 
      - name: Check cache 
        run: |
          echo "upstream_heads=$(git ls-remote https://github.com/roothide/theos | head -n1 | cut -f1)-$(git ls-remote https://github.com/theos/sdks | head -n1 | cut -f1)" >> $GITHUB_ENV 
 
      - name: Use cache 
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/theos 
          key: ${{ runner.os }}-${{ env.upstream_heads }}
 
      # 后续构建步骤（略，与原配置一致）