# .github/workflows/sync-fork.yml
name: Auto Sync Fork

on:
  schedule:
    - cron: "0 0 * * *"  # 每天UTC时间0点自动执行
  workflow_dispatch:     # 支持手动触发

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 必须授予写入权限才能推送代码

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add upstream https://github.com/ORIGINAL_OWNER/ORIGINAL_REPO.git
          git fetch upstream --prune

      - name: Merge main branch
        run: |
          git checkout main
          git merge --ff-only upstream/main
          git push origin main

      - name: Sync tags
        run: |
          git fetch upstream --tags
          git push origin --tags

      - name: Conflict handler
        if: failure()
        run: |
          git merge --abort
          echo "检测到冲突，请手动处理：https://github.com/${{ github.repository }}/actions"